"""Add urgency field to inquiry specifications

Revision ID: 9f90df26edf7
Revises: aa2be70b53e7
Create Date: 2026-08-21 12:29:22.759855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f90df26edf7'
down_revision = 'aa2be70b53e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgency', sa.Enum('standard', 'urgent (1-2 days)', 'rush (same/next day)', name='inquiry_urgency'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry_specifications', schema=None) as batch_op:
        batch_op.drop_column('urgency')

    # ### end Alembic commands ###
