"""Initial tables

Revision ID: aa2be70b53e7
Revises: 
Create Date: 2026-08-21 11:35:29.793185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2be70b53e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'print_shop', 'admin', name='user_role'), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_location', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('print_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('business_address', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='shop_approval_status'), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('completed_orders_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('print_category_id', sa.Integer(), nullable=False),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('predicted_price_min', sa.Float(), nullable=True),
    sa.Column('predicted_price_max', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'closed', name='inquiry_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['print_category_id'], ['print_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_shop_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['print_shop_id'], ['print_shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_shop_id', sa.Integer(), nullable=False),
    sa.Column('print_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['print_category_id'], ['print_categories.id'], ),
    sa.ForeignKeyConstraint(['print_shop_id'], ['print_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('print_shop_id', 'print_category_id', name='uq_shop_category')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('print_shop_id', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=False),
    sa.Column('estimated_completion_days', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='bid_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['print_shop_id'], ['print_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id', 'print_shop_id', name='uq_inquiry_shop_bid')
    )
    op.create_table('inquiry_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('standard_size', sa.String(length=10), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('paper_type', sa.String(length=50), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('colour_mode', sa.String(length=20), nullable=True),
    sa.Column('sides', sa.String(length=20), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('finishing_type', sa.String(length=50), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('delivery_method', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('print_shop_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Confirmed', 'In Production', 'Ready', 'Dispatched', 'Delivered', 'Completed', 'Cancelled', name='order_status'), nullable=False),
    sa.Column('delivery_method', sa.Enum('self-collection', 'delivery', 'island-wide courier', name='order_delivery_method'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['print_shop_id'], ['print_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid_id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('raised_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'rejected', name='dispute_status'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Confirmed', 'In Production', 'Ready', 'Dispatched', 'Delivered', 'Completed', 'Cancelled', name='order_status_history_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('print_shop_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['print_shop_id'], ['print_shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('simulated_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('suggested_advance_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'simulated_paid', name='simulated_payment_status'), nullable=False),
    sa.Column('simulated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulated_payments')
    op.drop_table('reviews')
    op.drop_table('order_status_history')
    op.drop_table('disputes')
    op.drop_table('orders')
    op.drop_table('inquiry_specifications')
    op.drop_table('bids')
    op.drop_table('shop_services')
    op.drop_table('portfolios')
    op.drop_table('inquiries')
    op.drop_table('print_shops')
    op.drop_table('customer_profiles')
    op.drop_table('users')
    op.drop_table('print_categories')
    # ### end Alembic commands ###
