"""Add is_active field to users

Revision ID: d26e959eee54
Revises: 9f90df26edf7
Create Date: 2026-08-22 15:07:33.264764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26e959eee54'
down_revision = '9f90df26edf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required here - without it, this fails
        # against any row that already exists, since it's a NOT NULL
        # column being added to a table that already has data.
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
